# Lee los valores desde las variables del servidor
spring.datasource.url=${DB_URL}
spring.datasourse.username=${DB_USERNAME}
spring.datasourse.password=${DB_PASSWORD}
spring.datasourse.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate / Dialecto para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate

