spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=demo

# =========================================================
# CONFIGURACION DE HIBERNATE / JPA
# =========================================================
# 'update' crea o actualiza las tablas automáticamente en la BD segun las entidades @Entity definidas.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de IntelliJ las consultas SQL que Hibernate ejecuta (Util para depuracion)
spring.jpa.show-sql=true